spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}}:5432/{DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    load balancer:
      ribbon:
        enable: true

fake-api:
  url: https://fakestoreapi.com

server:
  port: 8080